Project1-main/force-app/main/default/objects/Parts_Order_List__c/Parts_Order_List__c.object-meta.xml
<CustomObject>
    <description>List of ordered parts</description>
    <label>Part Order List</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts Order List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project1-main/Project1-main/Project2/force-app/main/default/objects/Parts_Order_List__c/fields/Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Part_Type__c</fullName>
    <label>Part Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parts_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Parts_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Decking</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
    </customValue>
    <customValue>
        <fullName>Outriggers</fullName>
    </customValue>
    <description>Picklist for parts</description>
    <masterLabel>Parts Picklist</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PartOrderEdit_Test.cls
@isTest 
private class PartOrderEdit_Test {
 
    @isTest
    private static void ControllerTest() {
        Test.startTest();
        Test.setCurrentPage(Page.PartOrderEditPage);
        // Test null controller for stdController getter 
        ApexPages.StandardSetController stdSetController = NULL;
        stdSetController = PartOrderEdit_CX.stdController;
        PartOrderEdit_CX extController = new PartOrderEdit_CX(stdSetController);
        Test.stopTest();
    }

    @isTest
    private static void PartTest() {
        List <Parts_Order_List__c> parts = new List<Parts_Order_List__c>();
        parts.add(new Parts_Order_List__c(Name = 'Test', Part_Type__c = 'Accessories'));
        insert parts;
    }

    
    @isTest
    private static void PartBulkTest() {
        List <Parts_Order_List__c> parts = new List<Parts_Order_List__c>();
        for(Integer i = 0;i < 200;i++) {
            parts.add(new Parts_Order_List__c(Name = 'Test', Part_Type__c = 'Accessories'));
        }
        insert parts;
    }

    @isTest
    private static void PartInvalidTest() {
        Parts_Order_List__c part = new Parts_Order_List__c();
        // part.Name='Test';
        // part.Part_Type__c = 'Accessories';

        // get result of record insertion (a failure in this case) 
        Test.startTest();
        Database.SaveResult insertionResult = Database.insert(part, false);
        Test.stopTest();

        Integer errorCount = 0;
        if(!insertionResult.isSuccess()) {
                System.debug('Received error.');
            ++errorCount;
        }

        System.assertEquals(0, errorCount);
    }
}