Project1-main/force-app/main/default/objects/Parts_Order_List__c/Parts_Order_List__c.object-meta.xml
<CustomObject>
    <description>List of ordered parts</description>
    <label>Part Order List</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts Order List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project1-main/Project1-main/Project2/force-app/main/default/objects/Parts_Order_List__c/fields/Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Part_Type__c</fullName>
    <label>Part Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parts_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Parts_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Decking</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
    </customValue>
    <customValue>
        <fullName>Outriggers</fullName>
    </customValue>
    <description>Picklist for parts</description>
    <masterLabel>Parts Picklist</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/newPartsController_Test.cls
@isTest
private class newPartsController_Test {
    @IsTest 
    static void partSaveTest() {
        Parts_Order_List__c part = new Parts_Order_List__c();
        newPartsController ControllerObj = new newPartsController();
        Test.startTest();
            ControllerObj.getParts();
            ControllerObj.step1();
            ControllerObj.step2();
            ControllerObj.step3();
            ControllerObj.cancel();
            ControllerObj.parts.Name = 'Deck';
            ControllerObj.parts.Part_Type__c = 'Decking';
            ControllerObj.save();
            apexPages.Currentpage().getParameters().put('Id',part.id);
        Test.stopTest();
    }
    @IsTest
    static void partBulkTest() {
        newPartsController ControllerObj = new newPartsController();
        Parts_Order_List__c part = new Parts_Order_List__c();
        Test.startTest();
        for(Integer i = 0;i < 100;i++) {
            ControllerObj.getParts();
            ControllerObj.step1();
            ControllerObj.step2();
            ControllerObj.step3();
            ControllerObj.cancel();
            ControllerObj.parts.Name = 'Test';
            ControllerObj.parts.Part_Type__c = 'Decking';
            ControllerObj.save();
            apexPages.Currentpage().getParameters().put('Id',part.id);
        }
        Test.stopTest();
    }
    @IsTest
    public static void  PartsInvalidTest() {
        newPartsController ControllerObj = new newPartsController();
        Parts_Order_List__c part = new Parts_Order_List__c();
        try {
            ControllerObj.getParts();
            ControllerObj.step1();
            ControllerObj.step2();
            ControllerObj.step3();
            ControllerObj.cancel();
            ControllerObj.parts.Part_Type__c = null;
            ControllerObj.save();
            apexPages.Currentpage().getParameters().put('Id',part.id);
        } catch (Exception ex) {
            if (ex.getMessage().contains('Part_Type__c is blank')) {
                System.assert(true);
            }else {
                system.assert(false);
            }
        }
    }
    @isTest(SeeAllData=true)
    static void RestrictedUserTest(){
        newPartsController ControllerObj = new newPartsController();
        Parts_Order_List__c part = new Parts_Order_List__c();
        Profile p = [SELECT id FROM Profile WHERE Name='Director of Sales'];
        User u = new user(Alias = 'direct', Email='director@test.org', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='DirectorofSales@testorg.net');
        Test.startTest();
        System.runAs(u){
            ControllerObj.getParts();
            ControllerObj.step1();
            ControllerObj.step2();
            ControllerObj.step3();
            ControllerObj.cancel();
            ControllerObj.parts.Name = 'Deck';
            ControllerObj.parts.Part_Type__c = 'Decking';
            ControllerObj.save();
            apexPages.Currentpage().getParameters().put('Id',part.id);
            
        }
        Test.stopTest();
        
    }
}