Project1-main/force-app/main/default/objects/Parts_Order_List__c/Parts_Order_List__c.object-meta.xml
<CustomObject>
    <description>List of ordered parts</description>
    <label>Part Order List</label>
    <nameField>
        <label>Part Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts Order List</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project1-main/force-app/main/default/objects/Parts_Order_List__c/fields/Expected_Arrival_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Arrival_Date__c</fullName>
    <description>Part expected delivery date</description>
    <label>Expected Arrival Date</label>
    <type>Date</type>
</CustomField>

Project1-main/Project1-main/Project2/force-app/main/default/objects/Parts_Order_List__c/fields/Part_Type__c.field-meta.xml
<CustomField>
    <fullName>Part_Type__c</fullName>
    <label>Part Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parts_Picklist</valueSetName>
    </valueSet>
</CustomField>

Project1-main/force-app/main/default/objects/Parts_Order_List__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Project1-main/force-app/main/default/objects/Parts_Order_List__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Supplier__c</referenceTo>
    <relationshipLabel>Parts Order List</relationshipLabel>
    <relationshipName>Parts_Order_List</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1-main/Project1-main/Project2/force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Parts_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accessories</fullName>
    </customValue>
    <customValue>
        <fullName>Decking</fullName>
    </customValue>
    <customValue>
        <fullName>Electronics</fullName>
    </customValue>
    <customValue>
        <fullName>Motor</fullName>
    </customValue>
    <customValue>
        <fullName>Outriggers</fullName>
    </customValue>
    <description>Picklist for parts</description>
    <masterLabel>Parts Picklist</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

Project1-main/force-app/main/default/classes/PartOrderEdit_CX.cls
public with sharing class PartOrderEdit_CX {
    
    @AuraEnabled
    public static List<Parts_Order_List__c> orderedParts() {
    	List<Parts_Order_List__c> Parts = new List<Parts_Order_List__c>([SELECT Id, Name, Part_Type__c, Quantity__c, Supplier__c, Date_Ordered__c, Expected_Arrival_Date__c FROM Parts_Order_List__c]);
      return Parts;  
    }
    /*
    public static ApexPages.StandardSetController stdController {
        get {
            if(stdController == null) {
                stdController = new ApexPages.StandardSetController(Parts);
            }
            return stdController;
        }
        set;
    }
    public PartOrderEdit_CX(ApexPages.StandardSetController Controller) {
        stdController = Controller;
    }
    
    
    public PageReference cancel() {
        PageReference pr = new PageReference('/'+Schema.SObjectType.Parts_Order_List__c.getKeyPrefix());
        pr.setRedirect(true);
        return pr;
    }
*/
    
    @AuraEnabled 
    Public static Parts_Order_List__c savePartsOrder(Parts_Order_List__c order){
        insert order;
        return order;
    }
    
    @AuraEnabled
    public static List<String> getPartType() {
        List<String> pickListValuesList = new List<String>();
        Schema.DescribeFieldResult fieldResult = Parts_Order_List__c.Part_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
            System.debug('Values in Rating are: '+pickListValuesList);
        }     
        return pickListValuesList;
    }
        
    }