Project1-main/Project1-main/Project2/force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project1-main/force-app/main/default/objects/Supplier__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Project1-main/force-app/main/default/classes/SearchSupplierController_Test.cls
@isTest
public with sharing class SearchSupplierController_Test {
    
    @isTest static void getSuppliersTest(){
        List<Supplier__c> recordData = SearchSupplierController.getSuppliers();
        List<Supplier__c> testData =  [SELECT Name, Phone__c, Website__c, Region__c, CreatedById FROM Supplier__c];

        System.assertEquals(recordData, testData);
    }


    @isTest static void testFindByName(){

        String searchKey = 'test';
        List<Supplier__c> recordData = SearchSupplierController.findByName(searchKey);

        List<Supplier__c> testData = [SELECT Name, Phone__c, Website__c, Region__c, CreatedById FROM Supplier__c WHERE Name LIKE:searchKey];
        
        System.assertEquals(recordData, testData);
    }
    
}