Project1-main/Project1-main/Project2/force-app/main/default/objects/Supplier__c/Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project1-main/force-app/main/default/objects/Supplier__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

Project1-main/force-app/main/default/classes/SearchSupplierController.cls
public with sharing class SearchSupplierController {
    @AuraEnabled
    public static List<Supplier__c> getSuppliers(){
        return [SELECT Name, Phone__c, Website__c, Region__c, CreatedById FROM Supplier__c];
    }
    @AuraEnabled
    public static List<Supplier__c> findByName(String searchKey){
        String name = + searchKey + '%';
        return [SELECT Name, Phone__c, Website__c, Region__c, CreatedById FROM Supplier__c WHERE Name LIKE:name];
    }
}