Project1-main/Project1-main/DeltaProject1/force-app/main/default/objects/Boat_Sold__c/Boat_Sold__c.object-meta.xml
<CustomObject>
    <label>Boat Sold</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats Sold</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1-main/Project1-main/Project2/force-app/main/default/objects/Boat_Sold__c/fields/Sold_to__c.field-meta.xml
<CustomField>
    <fullName>Sold_to__c</fullName>
    <description>Who the boat was sold to.</description>
    <label>Sold to</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Boats Sold</relationshipLabel>
    <relationshipName>Boats_Sold</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Project1-main/Project1-main/DeltaProject1/force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project1-main/Project1-main/DeltaProject1/force-app/main/default/classes/CustomerDeletionHandler.cls
public with sharing class CustomerDeletionHandler {
    public static void CustomerDeletionPrevention(Map<Id,Customer__c> m) {
        
        for (Customer__c c : [SELECT Id FROM Customer__c WHERE Id IN (SELECT Sold_to__c FROM Boat_Sold__c) 
                            AND Id IN :Trigger.old]) {

            Trigger.oldMap.get(c.Id).addError( 
                'Cannot delete customer who purchased a boat.');
        }
    }
}