Project1-main/Project1-main/DeltaProject1/force-app/main/default/objects/Boat_Sold__c/Boat_Sold__c.object-meta.xml
<CustomObject>
    <label>Boat Sold</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats Sold</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Boat_Sold__c/fields/Boat_Type_Inshore__c.field-meta.xml
<CustomField>
    <fullName>Boat_Type_Inshore__c</fullName>
    <label>Boat Type Inshore</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type_Inshore</valueSetName>
    </valueSet>
</CustomField>

Project1-main/Project1-main/Project2/force-app/main/default/objects/Boat_Sold__c/fields/Boat_Type_Offshore__c.field-meta.xml
<CustomField>
    <fullName>Boat_Type_Offshore__c</fullName>
    <label>Boat Type Offshore</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Boat_Type_Offshore</valueSetName>
    </valueSet>
</CustomField>

Project1-main/force-app/main/default/globalValueSets/Boat_Type_Inshore.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Bay</fullName>
    </customValue>
    <customValue>
        <fullName>Center Console</fullName>
    </customValue>
    <customValue>
        <fullName>Flats</fullName>
    </customValue>
    <masterLabel>Boat Type Inshore</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Boat_Type_Offshore.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Center Console</fullName>
    </customValue>
    <customValue>
        <fullName>Convertible</fullName>
    </customValue>
    <customValue>
        <fullName>Walkaround</fullName>
    </customValue>
    <masterLabel>Boat Type Offshore</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BoatSoldController.cls
public class BoatSoldController {
    
    // This member variable maintain the state of the wizard.
   // When users enter data into the wizard, their input is stored
   // in these variables. 
   public Boat_Sold__c boatsold;
   Integer boattype;

   public Pagereference boat1() {
        boattype = 1;
        return Page.CreateBoat;
    }
   
   public Pagereference boat2() {
        boattype = 2;
        return Page.CreateBoat;
    }

    public Pagereference boat3() {
        boattype = 3;
        return Page.CreateBoat;
    }

    public Pagereference boat4() {
        boattype = 4;
        return Page.CreateBoat;
    }

    public Pagereference boat5() {
        boattype = 5;
        return Page.CreateBoat;
    }

    public Pagereference boat6() {
        boattype = 6;
        return Page.CreateBoat;
    }


   
   // This method returns filled out data for one picklist
   public Boat_Sold__c getBoatSold() {
      if(boatsold == null) boatsold = new Boat_Sold__c();
      switch on boattype {
          when 1 {
              boatsold.Boat_Type_Inshore__c = 'Bay';
          }
          when 2 {
              boatsold.Boat_Type_Inshore__c = 'Center Console';
          }
          when 3 {
            boatsold.Boat_Type_Inshore__c = 'Flats';
          }
          when 4 {
            boatsold.Boat_Type_Offshore__c = 'Center Console';
          } 
          when 5 {
            boatsold.Boat_Type_Offshore__c = 'Convertible';
          } 
          when 6 {
            boatsold.Boat_Type_Offshore__c = 'Walkaround';
          }
          
      }
      return boatsold;
   }
    
   // This method cancels the wizard, and returns the user to the 
   // Boat_Sold Page
    public PageReference cancel() {
      PageReference boatPage = new PageReference('/'+ Schema.SObjectType.Boat_Sold__c.getKeyPrefix());
      boatPage.setRedirect(true);
      return boatPage; 
    }

   // This method performs save for the Boat_Sold, and
   // then returns the user to the Boat_Sold Home page.
   public PageReference save() {
        insert boatsold;
       
        PageReference boatPage = new PageReference('/'+ Schema.SObjectType.Boat_Sold__c.getKeyPrefix());
        boatPage.setRedirect(true);

        return boatPage;
    }
    
    public PageReference Bayinshore() {
        return Page.Bayinshore;
    }
     
    public PageReference Centerinshore() {
        return Page.Centerinshore;
    }    
    
    public PageReference Flatinshore() {
        return Page.Flatinshore;
    }
     
    public PageReference Centeroffshore() {
        return Page.Centeroffshore;
    }
    
    public PageReference Convertibleoffshore() {
        return Page.Convertibleoffshore;
    }
    
    public PageReference Walkaroundoffshore() {
        return Page.Walkaroundoffshore;
    }
}