Project1-main/Project1-main/DeltaProject1/force-app/main/default/objects/Boat_Sold__c/Boat_Sold__c.object-meta.xml
<CustomObject>
    <label>Boat Sold</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats Sold</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1-main/force-app/main/default/objects/Boat_Sold__c/fields/Email_of_Customer__c.field-meta.xml
<CustomField>
    <fullName>Email_of_Customer__c</fullName>
    <label>Email of Customer</label>
    <type>Email</type>
</CustomField>

Project1-main/Project1-main/DeltaProject1/force-app/main/default/objects/Boat_Sold__c/fields/Price_Of_Boat__c.field-meta.xml
<CustomField>
    <fullName>Price_Of_Boat__c</fullName>
    <label>Price Of Boat</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Project1-main/Project1-main/Project2/force-app/main/default/objects/Boat_Sold__c/fields/Sold_to__c.field-meta.xml
<CustomField>
    <fullName>Sold_to__c</fullName>
    <description>Who the boat was sold to.</description>
    <label>Sold to</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Boats Sold</relationshipLabel>
    <relationshipName>Boats_Sold</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Project1-main/Project1-main/DeltaProject1/force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Customer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Project1-main/force-app/main/default/classes/BoatSoldControllerTest.cls
@isTest
public class BoatSoldControllerTest {

    //  Boat_Sold__c b = new Boat_Sold__c(Name= 'Boat1', Source__c='Web',  
    //   Works__c='Gen Repairs', S);
    //   insert b;
       
 //    Test.StartTest();
 //       pageRef.getParameters().put('Id', String.valueOf(b.Id));
  //System.assertEquals(null, pg); //assertion
    
    @isTest public static void BayBoat1Test(){
       
     PageReference pageRef = Page.Bayinshore;
     //   Test.setCurrentPage(pageRef);
              
     BoatSoldController cntr = new BoatSoldController();
     PageReference pg = cntr.Bayinshore();
     System.assertNotEquals(null, pg); 
    }

    @isTest public static void CenterinshoreBoat1test(){
       
        PageReference pageRef = Page.Centerinshore;
        //   Test.setCurrentPage(pageRef);
                 
        BoatSoldController cntr = new BoatSoldController();
          PageReference pg = cntr.Centerinshore();
          System.assertNotEquals(null, pg); //assertion
       }

       @isTest public static void FlatinshoreBoat1test(){
       
         PageReference pageRef = Page.Flatinshore;
         //   Test.setCurrentPage(pageRef);
                  
         BoatSoldController cntr = new BoatSoldController();
           PageReference pg = cntr.Flatinshore();
           System.assertNotEquals(null, pg); //assertion
        }
        @isTest public static void CenteroffshoreBoat1test(){
       
         PageReference pageRef = Page.Centeroffshore;
         //   Test.setCurrentPage(pageRef);
                  
         BoatSoldController cntr = new BoatSoldController();
           PageReference pg = cntr.Centeroffshore();
           System.assertNotEquals(null, pg); //assertion
        }
        @isTest public static void ConvertibleoffshoreBoat1test(){
       
         PageReference pageRef = Page.Convertibleoffshore;
         //   Test.setCurrentPage(pageRef);
                  
         BoatSoldController cntr = new BoatSoldController();
           PageReference pg = cntr.Convertibleoffshore();
           System.assertNotEquals(null, pg); //assertion
        }
        @isTest public static void WalkaroundoffshoreBoat1test(){
       
         PageReference pageRef = Page.Walkaroundoffshore;
         //   Test.setCurrentPage(pageRef);
                  
         BoatSoldController cntr = new BoatSoldController();
           PageReference pg = cntr.Walkaroundoffshore();
           System.assertNotEquals(null, pg); //assertion
        }

        @isTest public static void BayBoat2Test(){
       
         PageReference pageRef = Page.Bayinshore;
         //   Test.setCurrentPage(pageRef);
                  
         BoatSoldController cntr = new BoatSoldController();
         PageReference pf = cntr.Bayinshore();
         PageReference pg = cntr.boat1();
         System.assertNotEquals(null, pg); 
        }
     
        @isTest public static void CenterinshoreBoat2test(){
           
            PageReference pageRef = Page.Centerinshore;
            //   Test.setCurrentPage(pageRef);
                     
            BoatSoldController cntr = new BoatSoldController();
              PageReference pf = cntr.Centerinshore();
              PageReference pg = cntr.boat2();
              System.assertNotEquals(null, pg); //assertion
           }
     
           @isTest public static void FlatinshoreBoat2test(){
           
             PageReference pageRef = Page.Flatinshore;
             //   Test.setCurrentPage(pageRef);
                      
             BoatSoldController cntr = new BoatSoldController();
               PageReference pf = cntr.Flatinshore();
               PageReference pg = cntr.boat3();
               System.assertNotEquals(null, pg); //assertion
            }
            @isTest public static void CenteroffshoreBoat2test(){
           
             PageReference pageRef = Page.Centeroffshore;
             //   Test.setCurrentPage(pageRef);
                      
             BoatSoldController cntr = new BoatSoldController();
               PageReference pf = cntr.Centeroffshore();
               PageReference pg = cntr.boat4();
               System.assertNotEquals(null, pg); //assertion
            }
            @isTest public static void ConvertibleoffshoreBoat2test(){
           
             PageReference pageRef = Page.Convertibleoffshore;
             //   Test.setCurrentPage(pageRef);
                      
             BoatSoldController cntr = new BoatSoldController();
               PageReference pf = cntr.Convertibleoffshore();
               PageReference pg = cntr.boat5();
               System.assertNotEquals(null, pg); //assertion
            }
            @isTest public static void WalkaroundoffshoreBoat2test(){
           
             PageReference pageRef = Page.Walkaroundoffshore;
             //   Test.setCurrentPage(pageRef);
                      
             BoatSoldController cntr = new BoatSoldController();
               PageReference pf = cntr.Walkaroundoffshore();
               PageReference pg = cntr.boat6();
               System.assertNotEquals(null, pg); //assertion
            }

            @isTest public static void WalkaroundoffshoreBoatCanceltest(){
           
               PageReference pageRef = Page.Walkaroundoffshore;
               //   Test.setCurrentPage(pageRef);
                        
               BoatSoldController cntr = new BoatSoldController();
                 PageReference pf = cntr.Walkaroundoffshore();
                 PageReference pg = cntr.boat6();
                 Pagereference pb = cntr.cancel();
                 System.assertNotEquals(null, pb); //assertion
              }
              @isTest public static void WalkaroundoffshoreBoatSavetest(){
           
               PageReference pageRef = Page.Walkaroundoffshore;
               //   Test.setCurrentPage(pageRef);
               //Customer__c c1 = [SELECT ID,NAME FROM CUSTOMER__C LIMIT 1];
               BoatSoldController cntr = new BoatSoldController();
                 PageReference pf = cntr.Walkaroundoffshore();
                 PageReference pg = cntr.boat6();
                 //cntr.boatsold(new Boat_Sold__c(name='dave'));
                 cntr.boatsold = new Boat_Sold__c();
                 cntr.boatsold.name = 'dave';
                 cntr.boatsold.Email_of_Customer__c = 'dws@gmail.com';
                 cntr.boatsold.Price_of_Boat__c = 45000;
                 cntr.boatsold.Sold_to__c = 'a025e000007BTe6AAG';
                 cntr.boatsold.Date_Sold__c = System.today();
                 cntr.getboatsold();
                 Pagereference pb = cntr.save();
                 System.assertNotEquals(null, pb); //assertion
              }

}