Project1-main/Project1-main/Project2/force-app/main/default/objects/Boat_Manufacturing__c/Boat_Manufacturing__c.object-meta.xml
<CustomObject>
    <description>Manufacturing Details for boats</description>
    <label>Boat Manufacturing</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Manufacturings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1-main/force-app/main/default/objects/Boat_Manufacturing__c/fields/Boat_Length__c.field-meta.xml
<CustomField>
    <fullName>Boat_Length__c</fullName>
    <label>Boat Length</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Project1-main/force-app/main/default/classes/BoatTestDataFactory.cls
@IsTest
public class BoatTestDataFactory {
    public static List <Boat_Manufacturing__c> BoatDataFactory(Integer numBoats){
        List<Boat_Manufacturing__c> boatList = new List<Boat_Manufacturing__c>();
        for(Integer i = 0; i<numBoats; i++){
            Boat_Manufacturing__c testBoat = new Boat_Manufacturing__c(Boat_Length__c = 'i', Name = 'testBoat' + i);
            boatList.add(testBoat);
        }
        insert boatList;
        return boatList;
    }
}