Project1-main/Project1-main/Project2/force-app/main/default/objects/Boat_Manufacturing__c/Boat_Manufacturing__c.object-meta.xml
<CustomObject>
    <description>Manufacturing Details for boats</description>
    <label>Boat Manufacturing</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Manufacturings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1-main/force-app/main/default/objects/Boat_Manufacturing__c/fields/Boat_Length__c.field-meta.xml
<CustomField>
    <fullName>Boat_Length__c</fullName>
    <label>Boat Length</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Project1-main/Project1-main/DeltaProject1/force-app/main/default/objects/Boat_Sold__c/Boat_Sold__c.object-meta.xml
<CustomObject>
    <label>Boat Sold</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats Sold</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1-main/Project1-main/Project2/force-app/main/default/objects/Boat_Sold__c/fields/Boat_Length__c.field-meta.xml
<CustomField>
    <fullName>Boat_Length__c</fullName>
    <label>Boat Length</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

Project1-main/force-app/main/default/classes/CreateBoatTriggerHandler.cls
public with sharing class CreateBoatTriggerHandler {
    
    public static void createBoatOnSave(List<Boat_Sold__c> bS){
        List<Boat_Manufacturing__c> bM = new List<Boat_Manufacturing__c>();
        for (Boat_Sold__c s : bS) {
            Boat_Manufacturing__c b = new Boat_Manufacturing__c(Name = s.Name,
                                                                Boat_Length__c = s.Boat_Length__c);

            bM.add(b);
        }
        insert bM;
    }
}